[package]
name = "exhaust-raid-24"
version = "0.1.0"
authors = ["Paul Blouët <1818316+Geogi@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
